export enum ActionTypes {
  SAVE_NOTE_START = "SAVE_NOTE_START",
  SAVE_NOTE_DONE = "SAVE_NOTE_DONE",
  SAVE_NOTE_ERROR = "SAVE_NOTE_ERROR",

  LOAD_NOTES_START = "LOAD_NOTES_START",
  LOAD_NOTES_DONE = "LOAD_NOTES_DONE",
  LOAD_NOTES_ERROR = "LOAD_NOTES_ERROR",
}
